const CLEAN_CELL = 0;
export const NO_COLLISION_WITH_ANOTHER_TETROMINO = "clear";

export const STAGE = {
  WIDTH: 12,
  HEIGHT: 20,
  EMPTY_CELL: [CLEAN_CELL, NO_COLLISION_WITH_ANOTHER_TETROMINO],
};
